# ********RoostGPT********

# Test generated by RoostGPT for test claude-karate using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /nobelPrize/{category}/{year}_get for http method type GET 
# RoostTestHash=00eb351b13
# 
# 

# ********RoostGPT********
Feature: Nobel Prize API

Background:
  * url target
  * def authToken = karate.properties['AUTH_TOKEN']

Scenario Outline: Get Nobel Prize information for a specific category and year
  Given path '/2.1/nobelPrize/<category>/<year>'
  And header Authorization = authToken
  When method GET
  Then status 200
  And match header Content-Type contains 'application/json'
  And match response.nobelPrize.awardYear == <year>
  And match response.nobelPrize.category.en == <categoryEn>
  And match response.nobelPrize.categoryFullName.en == <categoryFullEn>
  And match response.nobelPrize.dateAwarded == '#string'
  And match response.nobelPrize.prizeAmount == '#number'
  And match response.nobelPrize.prizeAmountAdjusted == '#number'
  And match response.nobelPrize.topMotivation.en == '#string'
  And match each response.nobelPrize.laureates contains { id: '#number', name: '#object', portion: '#string', sortOrder: '#string', motivation: '#object' }
  
  Examples:
    | category | year | categoryEn  | categoryFullEn             |
    | che      | 2020 | Chemistry   | The Nobel Prize in Chemistry |
    | eco      | 2019 | Economics   | The Sveriges Riksbank Prize in Economic Sciences in Memory of Alfred Nobel |
    | lit      | 2018 | Literature  | The Nobel Prize in Literature |
    | pea      | 2017 | Peace       | The Nobel Peace Prize |
    | phy      | 2016 | Physics     | The Nobel Prize in Physics |
    | med      | 2015 | Medicine    | The Nobel Prize in Physiology or Medicine |

Scenario Outline: Get Nobel Prize information with invalid category
  Given path '/2.1/nobelPrize/<category>/<year>'
  And header Authorization = authToken  
  When method GET
  Then status 400
  And match header Content-Type contains 'application/json'
  And match response.code == '400'
  And match response.message == 'Bad request.The request could not be understood by the server due to malformed syntax, modifications needed.'

  Examples:
    | category | year |
    | invalid  | 2020 |

Scenario Outline: Get Nobel Prize information for a future year
  Given path '/2.1/nobelPrize/<category>/<year>'
  And header Authorization = authToken
  When method GET
  Then status 404
  And match header Content-Type contains 'application/json'
  And match response.code == '404' 
  And match response.message == 'Not Found. The requested resource could not be found but may be available again in the future.'

  Examples:
    | category | year |
    | che      | 2100 |

Scenario Outline: Get Nobel Prize information for a year before 1901
  Given path '/2.1/nobelPrize/<category>/<year>'  
  And header Authorization = authToken
  When method GET
  Then status 422
  And match header Content-Type contains 'application/json'
  And match response.code == '422'
  And match response.message == 'Unprocessable Entity. The request was well-formed but was unable to be followed due to semantic errors.'
  
  Examples:
    | category | year |
    | phy      | 1800 |
