/*
Test generated by RoostGPT for test metering-integration-rest using AI Type Vertex AI and AI Model code-bison-32k

{
  background: null,
  rule: null,
  scenario: 'Create Metering Label\n' +
    '    When I send a POST request to "/v2.0/metering/metering-labels" with the following payload:\n' +
    '      """\n' +
    '      {\n' +
    '        "id": "bc91b832-8465-40a7-a5d8-ba87de442266",\n' +
    '        "tenant_id": "45345b0ee1ea477fac0f541b2cb79cd4",\n' +
    '        "description": "description of label1",\n' +
    '        "name": "label1"\n' +
    '      }\n' +
    '      """\n' +
    '    Then the response status code should be 201\n' +
    '    And the response should be in JSON\n' +
    '    And the response should contain the created metering label:\n' +
    '      | id                                   | tenant_id                           | description            | name   |\n' +
    '      | bc91b832-8465-40a7-a5d8-ba87de442266 | 45345b0ee1ea477fac0f541b2cb79cd4   | description of label1 | label1 |',
  title: 'Create Metering Label'
}

*/
 package org.commonjava.maven.ext.RoostTest;

import com.jayway.restassured.RestAssured;
import com.jayway.restassured.http.ContentType;
import com.jayway.restassured.specification.RequestSpecification;
import org.testng.annotations.Test;

import static com.jayway.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import static org.hamcrest.Matchers.equalTo;

public class createMeteringLabelTest {

    @Test
    public void createMeteringLabel() {
        RestAssured.baseURI = "{{ROOST_SERVER_URL}}";

        String payload = "{\n" +
                "        \"id\": \"bc91b832-8465-40a7-a5d8-ba87de442266\",\n" +
                "        \"tenant_id\": \"45345b0ee1ea477fac0f541b2cb79cd4\",\n" +
                "        \"description\": \"description of label1\",\n" +
                "        \"name\": \"label1\"\n" +
                "      }";

        given().
                contentType(ContentType.JSON).
                body(payload).
        when().
                post("/v2.0/metering/metering-labels").
        then().
                assertThat().
                statusCode(201).
                and().
                contentType(ContentType.JSON).
                and().
                body("id", equalTo("bc91b832-8465-40a7-a5d8-ba87de442266")).
                and().
                body("tenant_id", equalTo("45345b0ee1ea477fac0f541b2cb79cd4")).
                and().
                body("description", equalTo("description of label1")).
                and().
                body("name", equalTo("label1"));
    }
}