/*
Test generated by RoostGPT for test metering-integration-rest using AI Type Vertex AI and AI Model code-bison-32k

{
  background: 'Given the API is available',
  rule: null,
  scenario: 'Create Metering Label\n' +
    '    When I send a POST request to "/v2.0/metering/metering-labels" with the following payload:\n' +
    '      """\n' +
    '      {\n' +
    '        "id": "bc91b832-8465-40a7-a5d8-ba87de442266",\n' +
    '        "tenant_id": "45345b0ee1ea477fac0f541b2cb79cd4",\n' +
    '        "description": "description of label1",\n' +
    '        "name": "label1"\n' +
    '      }\n' +
    '      """\n' +
    '    Then the response status code should be 201\n' +
    '    And the response should be in JSON\n' +
    '    And the response should contain the created metering label:\n' +
    '      | id                                   | tenant_id                           | description            | name   |\n' +
    '      | bc91b832-8465-40a7-a5d8-ba87de442266 | 45345b0ee1ea477fac0f541b2cb79cd4   | description of label1 | label1 |',
  title: 'Create Metering Label'
}

*/
 package org.commonjava.maven.ext.RoostTest;

import static io.restassured.RestAssured.given;
import io.restassured.builder.RequestSpecBuilder;
import io.restassured.filter.log.LogDetail;
import io.restassured.http.ContentType;
import io.restassured.parsing.Parser;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

@DisplayName("Create Metering Label Test")
public class createMeteringLabelTest {
    private static RequestSpecification requestSpec;

    @BeforeAll
    public static void setup() {
        requestSpec = new RequestSpecBuilder()
                .setBaseUri(System.getenv("{{ROOST_SERVER_URL}}"))
                .setContentType(ContentType.JSON)
                .setAccept(ContentType.JSON)
                .log(LogDetail.ALL)
                .build();
    }

    @Test
    public void createMeteringLabel() {
        // Given the API is available

        // When I send a POST request to "/v2.0/metering/metering-labels" with the following payload:
        String payload = "{\n" +
                "        \"id\": \"bc91b832-8465-40a7-a5d8-ba87de442266\",\n" +
                "        \"tenant_id\": \"45345b0ee1ea477fac0f541b2cb79cd4\",\n" +
                "        \"description\": \"description of label1\",\n" +
                "        \"name\": \"label1\"\n" +
                "      }";

        // Then the response status code should be 201
        // And the response should be in JSON
        // And the response should contain the created metering label:
        Map<String, Object> expectedResponse = new HashMap<>();
        expectedResponse.put("id", "bc91b832-8465-40a7-a5d8-ba87de442266");
        expectedResponse.put("tenant_id", "45345b0ee1ea477fac0f541b2cb79cd4");
        expectedResponse.put("description", "description of label1");
        expectedResponse.put("name", "label1");

        Response response = given(requestSpec)
                .body(payload)
                .post("/v2.0/metering/metering-labels");

        response.then()
                .statusCode(201)
                .contentType(ContentType.JSON)
                .body("id", expectedResponse.get("id"))
                .body("tenant_id", expectedResponse.get("tenant_id"))
                .body("description", expectedResponse.get("description"))
                .body("name", expectedResponse.get("name"));
    }
}