/*
Test generated by RoostGPT for test metering-integration-rest using AI Type Vertex AI and AI Model code-bison-32k

{
  background: null,
  rule: null,
  scenario: 'Delete Metering Label\n' +
    '    When I send a DELETE request to "/v2.0/metering/metering-labels/a6700594-5b7a-4105-8bfe-723b346ce866"\n' +
    '    Then the response status code should be 204',
  title: 'Delete Metering Label'
}

*/
 package org.commonjava.maven.ext.RoostTest;

import io.restassured.RestAssured;
import io.restassured.config.SSLConfig;
import io.restassured.http.ContentType;
import org.apache.http.HttpStatus;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.HashMap;
import java.util.Map;

import static io.restassured.RestAssured.given;
import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * DeleteMeteringLabelTest class holds the test cases to verify delete metering label functionality.
 *
 * @author anil
 */
@DisplayName("Delete Metering Label")
public class DeleteMeteringLabelTest {
    private static final String ROOST_SERVER_URL = System.getenv("ROOST_SERVER_URL");

    private static final String METER_ID = "a6700594-5b7a-4105-8bfe-723b346ce866";

    private static final String API_SPEC_URL = ROOST_SERVER_URL + "/v2.0/metering/metering-labels/{metering_label_id}";

    @Test
    @DisplayName("Delete Metering Label")
    void deleteMeteringLabel() {
        // Create headers
        Map<String, String> headers = new HashMap<>();
        headers.put("Content-Type", ContentType.JSON.toString());

        // Delete metering label
        given()
                .config(RestAssured.config().sslConfig(new SSLConfig().relaxedHTTPSValidation()))
                .baseUri(API_SPEC_URL)
                .headers(headers)
                .pathParam("metering_label_id", METER_ID)
                .delete()
                .then()
                .statusCode(HttpStatus.SC_NO_CONTENT);
    }
}