/*
Test generated by RoostGPT for test metering-integration-rest using AI Type Vertex AI and AI Model code-bison-32k

{
  background: null,
  rule: null,
  scenario: 'Delete Metering Label Rule\n' +
    '    When I send a DELETE request to "/v2.0/metering/metering-label-rules/9536641a-7d14-4dc5-afaf-93a973ce0eb8"\n' +
    '    Then the response status code should be 204',
  title: 'Delete Metering Label Rule'
}

*/
 package org.commonjava.maven.ext.RoostTest;

import io.restassured.RestAssured;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.HashMap;
import java.util.Map;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.equalTo;

public class DeleteMeteringLabelRuleTest {

    @Test
    @DisplayName("Delete Metering Label Rule")
    void deleteMeteringLabelRule() {
        Map<String, Object> headers = new HashMap<>();
        headers.put("Content-Type", "application/json");

        given().
            headers(headers).
        when().
            delete("{{ROOST_SERVER_URL}}/v2.0/metering/metering-label-rules/9536641a-7d14-4dc5-afaf-93a973ce0eb8").
        then().
            statusCode(204);
    }
}