/*
Test generated by RoostGPT for test metering-integration-rest using AI Type Vertex AI and AI Model code-bison-32k

{
  background: 'Given the API is available',
  rule: null,
  scenario: 'Delete Metering Label\n' +
    '    When I send a DELETE request to "/v2.0/metering/metering-labels/a6700594-5b7a-4105-8bfe-723b346ce866"\n' +
    '    Then the response status code should be 204',
  title: 'Delete Metering Label'
}

*/
package org.commonjava.maven.ext.RoostTest;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.hasKey;
import static org.hamcrest.Matchers.is;
import static org.hamcrest.Matchers.notNullValue;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

@Tag("roost")
public class DeleteMeteringLabelTest {

    @Test
    @DisplayName("Delete Metering Label")
    void deleteMeteringLabel() {
        // Given the API is available

        // When I send a DELETE request to "/v2.0/metering/metering-labels/a6700594-5b7a-4105-8bfe-723b346ce866"
        given()
                .baseUri(System.getenv("{{ROOST_SERVER_URL}}"))
                .basePath("/v2.0/metering/metering-labels/a6700594-5b7a-4105-8bfe-723b346ce866")
                .when()
                .delete()

                // Then the response status code should be 204
                .then()
                .statusCode(204);
    }
}
