// Test generated by RoostGPT for test restA-gpt4-kore using AI Type Open AI and AI Model gpt-4

// Test generated for /deposit_post for http method type POST in rest-assured framework

// RoostTestHash=70db6d5eac

package org.commonjava.maven.ext;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.Test;
import org.junit.Assert;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;

public class DepositPostTest {

    @Test
    public void depositPostTest() {
        RestAssured.baseURI = System.getenv("BASE_URL");

        try (BufferedReader reader = new BufferedReader(new FileReader("src/test/java/org/commonjava/maven/ext/RoostTest/deposit_post.csv"))) {
            String headerLine = reader.readLine();
            String[] headers = headerLine.split(",");

            String line;
            while ((line = reader.readLine()) != null) {
                String[] data = line.split(",");

                Map<String, String> map = new HashMap<>();
                for (int i = 0; i < headers.length; i++) {
                    map.put(headers[i], data[i]);
                }

                Response response = given()
                        .pathParam("koreUserId", map.get("koreUserId"))
                        .pathParam("botId", map.get("botId"))
                        .pathParam("accountId", map.get("accountId"))
                        .header("Authorization", map.get("Authorization")) // Authorization is usually set in header, not as pathParam.
                        .contentType(ContentType.JSON)
                        .body(createRequestBody(map))
                        .when()
                        .post("/deposit")
                        .then()
                        .extract().response();

                validateResponse(response);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private String createRequestBody(Map<String, String> map) {
        return "{\n" +
                "  \"customerId\": \"" + map.get("customerId") + "\",\n" +
                "  \"sourceAccountId\": \"" + map.get("sourceAccountId") + "\",\n" +
                "  \"amount\": \"" + map.get("amount") + "\",\n" +
                "  \"currency\": \"" + map.get("currency") + "\",\n" +
                "  \"image\": \"" + map.get("image") + "\"\n" +
                "}";
    }

    private void validateResponse(Response response) {
        int statusCode = response.statusCode();
        switch (statusCode) {
            case 200:
                System.out.println("Description: Deposit success");
                break;
            case 401:
                System.out.println("Description: Error: Authorization failed.");
                validateErrorResponse(response);
                break;
            case 404:
                System.out.println("Description: Error: Not Found");
                validateNotFoundResponse(response);
                break;
            default:
                System.out.println("Description: Error: Unprocessable Entity");
                validateUnprocessableEntityResponse(response);
                break;
        }
    }

    private void validateErrorResponse(Response response) {
        Assert.assertThat(response.jsonPath().get("err.message"), instanceOf(String.class));
    }

    private void validateNotFoundResponse(Response response) {
        Assert.assertThat(response.jsonPath().get("err.message"), instanceOf(String.class));
    }

    private void validateUnprocessableEntityResponse(Response response) {
        Assert.assertThat(response.jsonPath().get("err.message"), instanceOf(String.class));
    }
}
