// Test generated by RoostGPT for test bankAssist-api using AI Type Open AI and AI Model gpt-4-1106-preview


// Test generated for /disputeTransaction_post for http method type POST in rest-assured framework

// RoostTestHash=a16706fdab

