// Test generated by RoostGPT for test restA-turbo-assistant-kore using AI Type Open AI and AI Model gpt-4-1106-preview

// Test generated for /GetAccountInfo_post for http method type POST in rest-assured framework

// RoostTestHash=8a95fbc531

