// Test generated by RoostGPT for test bankAssist-api using AI Type Open AI and AI Model gpt-4-1106-preview


// Test generated for /GetCCSchedule_post for http method type POST in rest-assured framework

// RoostTestHash=b38ec5fe10

// ... [rest of test class]

private void validateUnauthorisedResponse(Response response) {
    assertThat("Authorisation failed message is not as expected", 
               response.jsonPath().get("message"), is("Error: Authorisation failed."));
    // Additional detailed assertions can be added here based on the 'err' schema
}

private void validateNotFoundResponse(Response response) {
    assertThat("Not Found message is not as expected", 
               response.jsonPath().get("message"), is("Error: Not Found"));
    // Additional detailed assertions can be added here based on the 'err' schema
}

// ... [rest of test class]

