// Test generated by RoostGPT for test restA-turbo-wo-asst-kore using AI Type Open AI and AI Model gpt-4-1106-preview

// Test generated for /GetRecurringTransfers_post for http method type POST in rest-assured framework

// RoostTestHash=7e03af5a84

