// Test generated by RoostGPT for test restA-gpt4-kore using AI Type Open AI and AI Model gpt-4

// Test generated for /GetTransactions_post for http method type POST in rest-assured framework

// RoostTestHash=207beafabe

package org.commonjava.maven.ext.RoostTest;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.Test;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.equalTo;

public class GetTransactionsPostTest {
  
    @Test  
    public void GetTransactions_post_Test() {  
        RestAssured.baseURI = System.getenv("BASE_URL");  
  
        // Read CSV file  
        try (BufferedReader reader = new BufferedReader(new FileReader("src/test/java/org/commonjava/maven/ext/RoostTest/GetTransactions_post.csv"))) {  
            String headerLine = reader.readLine();  
            String[] headers = headerLine.split(",");  
  
            String line;  
            while ((line = reader.readLine()) != null) {  
                String[] data = line.split(",");  
  
                // Create a map of header to data  
                Map<String, String> map = new HashMap<>();  
                for (int i = 0; i < headers.length; i++) {  
                    map.put(headers[i], data[i]);  
                }  

                Response response = given()
				.pathParam("koreUserId", map.get("koreUserId"))
				.pathParam("botId", map.get("botId"))
				.pathParam("accountId", map.get("accountId"))
				.pathParam("Authorization", map.get("Authorization"))
				.pathParam("X-Auth-token", map.get("X-Auth-token"))
				.pathParam("X-CORRELATION-ID", map.get("X-CORRELATION-ID"))
				.contentType(ContentType.JSON)
				.body("{\n"+
					"  \"customerId\": \"" + map.get("customerId") + "\",\n" +
					"  \"accountNumber\": \"" + map.get("accountNumber") + "\",\n" +
					"  \"numOfTransactions\": \"" + map.get("numOfTransactions") + "\",\n" +
					"  \"status\": \"" + map.get("status") + "\",\n" +
					"  \"startDate\": \"" + map.get("startDate") + "\",\n" +
					"  \"endDate\": \"" + map.get("endDate") + "\",\n" +
					"  \"sort\": \"" + map.get("sort") + "\",\n" +
					"  \"transactionAmount\": \"" + map.get("transactionAmount") + "\",\n" +
					"  \"category\": \"" + map.get("category") + "\",\n" +
					"  \"debitOrCredit\": \"" + map.get("debitOrCredit") + "\n" +
 				"}")
                .when()
                .post("/GetTransactions")  
                .then() 
                .extract().response();    
         
                // Validate response
                validateResponse(response);
            }  
        } catch (IOException e) {  
            e.printStackTrace();  
        }  
    }

    private void validateResponse(Response response) {
        int statusCode = response.getStatusCode();

        switch(statusCode) {
            case 200:
                System.out.println("Description: successful operation");
                break;
            case 400:
                validateErrorResponse(response);
                break;
            case 404:
                validateNotFoundResponse(response);
                break;
            case 422:
                validateUnprocessableEntityResponse(response);
                break;
            default:
                System.out.println("Unexpected status code: " + statusCode);
        }
    }

    private void validateErrorResponse(Response response) {
        response.then().body("code", equalTo(400));
        response.then().body("message", equalTo("Bad Request"));
    }

    private void validateNotFoundResponse(Response response) {
        response.then().body("code", equalTo(404));
        response.then().body("message", equalTo("Not Found"));
    }

    private void validateUnprocessableEntityResponse(Response response) {
        response.then().body("code", equalTo(422));
        response.then().body("message", equalTo("Unprocessable Entity"));
    }
}
