// Test generated by RoostGPT for test bankAssist-api using AI Type Open AI and AI Model gpt-4-1106-preview


// Test generated for /personalInfoValidation_post for http method type POST in rest-assured framework

// RoostTestHash=be461d4c4c

<dependencies>
    <!-- Other existing dependencies -->
    
    <!-- Rest Assured for API testing -->
    <dependency>
        <groupId>io.rest-assured</groupId>
        <artifactId>rest-assured</artifactId>
        <version>{version}</version>
        <scope>test</scope>
    </dependency>
    
    <!-- JUnit for running tests -->
    <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <version>{version}</version>
        <scope>test</scope>
    </dependency>
    
    <!-- Hamcrest for assertions -->
    <dependency>
        <groupId>org.hamcrest</groupId>
        <artifactId>hamcrest-library</artifactId>
        <version>{version}</version>
        <scope>test</scope>
    </dependency>
</dependencies>

