// Test generated by RoostGPT for test restA-turbo-assistant-kore using AI Type Open AI and AI Model gpt-4-1106-preview

// Test generated for /resetPassword_post for http method type POST in rest-assured framework

// RoostTestHash=79c3f016d8

