/*
Test generated by RoostGPT for test metering-integration-rest using AI Type Vertex AI and AI Model code-bison-32k

{
  background: 'Given the API is available',
  rule: null,
  scenario: 'Show Metering Label\n' +
    '    When I send a GET request to "/v2.0/metering/metering-labels/a6700594-5b7a-4105-8bfe-723b346ce866"\n' +
    '    Then the response status code should be 200\n' +
    '    And the response should be in JSON\n' +
    '    And the response should contain the metering label:\n' +
    '      | id                                   | tenant_id                           | description            | name   |\n' +
    '      | a6700594-5b7a-4105-8bfe-723b346ce866 | 45345b0ee1ea477fac0f541b2cb79cd4   | label1 description     | label1 |',
  title: 'Show Metering Label'
}

*/
package org.commonjava.maven.ext.RoostTest;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.hasKey;

import io.quarkus.test.junit.QuarkusTest;
import io.restassured.RestAssured;
import io.restassured.parsing.Parser;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

@QuarkusTest
public class showMeteringLabelTest {

    @BeforeAll
    public static void setup() {
        RestAssured.baseURI = System.getenv("{{ROOST_SERVER_URL}}");
        RestAssured.registerParser("text/plain", Parser.TEXT);
    }

    @Test
    @DisplayName("Show Metering Label")
    public void showMeteringLabelTest() {
        String metering_label_id = "a6700594-5b7a-4105-8bfe-723b346ce866";
        Map<String, Object> headers = new HashMap<>();
        headers.put("Accept", "application/json");

        given().headers(headers)
                .when().get("/v2.0/metering/metering-labels/" + metering_label_id)
                .then()
                .statusCode(200)
                .contentType("application/json")
                .body("$", hasKey("id"))
                .body("$", hasKey("tenant_id"))
                .body("$", hasKey("description"))
                .body("$", hasKey("name"))
                .body("id", equalTo(metering_label_id))
                .body("tenant_id", equalTo("45345b0ee1ea477fac0f541b2cb79cd4"))
                .body("description", equalTo("label1 description"))
                .body("name", equalTo("label1"));
    }
}
