// Test generated by RoostGPT for test rbi-swagger using AI Type Azure Open AI and AI Model roostgpt-4-32k


// Test generated for /v1/accounts/{account-Id}/transactions_get for http method type GET in rest-assured framework


// RoostTestHash=2b28de8802


package org.commonjava.maven.ext.RoostTest;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import static org.junit.Assert.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.List;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class transactionsGetTest {
  
    @Test  
    public void transactionsGet_Test() {  
        RestAssured.baseURI = System.getenv("BASE_URL");  
  
        // Read CSV file  
        try (BufferedReader reader = new BufferedReader(new FileReader("src" + File.separator + "test" + File.separator + "java" + File.separator + "org" + File.separator + "commonjava" + File.separator + "maven" + File.separator + "ext" + File.separator + "RoostTest" + File.separator + "transactionsGetTest.csv"))) {  
            String headerLine = reader.readLine();  
            String[] headers = headerLine.split(",");  
  
            String line;  
            while ((line = reader.readLine()) != null) {  
                String[] data = line.split(",");  
  
                // Create a map of header to data  
                Map<String, String> map = new HashMap<>();  
                for (int i = 0; i < headers.length; i++) {  
                    map.put(headers[i], data[i]);  
                }  
                
  
                Response response = given()
				.pathParam("account-Id", map.get("account-Id") != null ? map.get("account-Id") : "")
				.pathParam("Consent-ID", map.get("Consent-ID") != null ? map.get("Consent-ID") : "")
				.pathParam("date_from", map.get("date_from") != null ? map.get("date_from") : "")
				.pathParam("bookingStatus", map.get("bookingStatus") != null ? map.get("bookingStatus") : "")
				.pathParam("withBalance", map.get("withBalance") != null ? map.get("withBalance") : "")
				.pathParam("date_to", map.get("date_to") != null ? map.get("date_to") : "")
				.pathParam("Content-Type", map.get("Content-Type") != null ? map.get("Content-Type") : "")
				.pathParam("PSU-ID", map.get("PSU-ID") != null ? map.get("PSU-ID") : "")
                .when()
                .get("/v1/accounts/{account-Id}/transactions")  
                .then() 
                .extract().response();    
         
                if (response.statusCode() == 200) {
					System.out.println("Description: Success");
				}
  
            }  
        } catch (IOException e) {  
            e.printStackTrace();  
        }  
    }
}
