// Test generated by RoostGPT for test restA-turbo-assistant-kore using AI Type Open AI and AI Model gpt-4-1106-preview

// Test generated for /UpdateCustomerInfo_put for http method type PUT in rest-assured framework

// RoostTestHash=89ddb90785

