// Test generated by RoostGPT for test restA-turbo-wo-asst-kore using AI Type Open AI and AI Model gpt-4-1106-preview

// Test generated for /UpdateScheduleTransfers_put for http method type PUT in rest-assured framework

// RoostTestHash=c0505709a3

