// ********RoostGPT********
/*
Test generated by RoostGPT for test rbi-swagger using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated for /v1/accounts/{account-Id}_get for http method type GET in rest-assured framework

RoostTestHash=58d301af11


*/

// ********RoostGPT********
package org.commonjava.maven.ext.RoostTest;
import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.Before;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import static org.junit.Assert.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.ArrayList;
import java.util.List;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.json.JSONObject;
import org.json.XML;
import org.json.JSONException;
import org.json.JSONArray;

public class v1AccountsAccountIdGetTest {

    List<Map<String, String>> envList = new ArrayList<>();


    @Before
    public void setUp() {
      TestdataLoader dataloader = new TestdataLoader();
      String[] envVarsList = {"account-Id"};
      envList = dataloader.load("src/test/java/org/commonjava/maven/ext/RoostTest/v1_accounts_account-IdGetTest.csv", envVarsList);
    }

  
    @Test  
    public void v1AccountsAccountIdGet_Test() {
        this.setUp();
        for (Map<String, String> testData : envList) {
          RestAssured.baseURI = (testData.get("BASE_URL") != null && !testData.get("BASE_URL").isEmpty()) ? testData.get("BASE_URL"): "http://xs2a.rbinternational.com";  
  
                Response responseObj = given()
				.header("Consent-ID", testData.get("Consent-ID") != null ? testData.get("Consent-ID") : "")
				.header("Content-Type", testData.get("Content-Type") != null ? testData.get("Content-Type") : "")
				.header("PSU-ID", testData.get("PSU-ID") != null ? testData.get("PSU-ID") : "")
				.queryParam("withBalance", testData.get("withBalance") != null ? testData.get("withBalance") : "")
				.pathParam("account-Id", testData.get("account-Id") != null ? testData.get("account-Id") : "")
                .when()
                .get("/v1/accounts/{account-Id}")  
                .then() 
                .extract().response(); 
              JsonPath response;
              String contentType = responseObj.getContentType();
              if (contentType.contains("application/xml") || contentType.contains("text/xml")) {
                String xmlResponse = responseObj.asString();
                JSONObject jsonResponse = XML.toJSONObject(xmlResponse);
                JSONObject jsonData = jsonResponse.getJSONObject("xml");
                String jsonString = jsonData.toString();
                response = new JsonPath(jsonString);
        
              } else {  
                response = responseObj.jsonPath(); 
              }  
         
                if (responseObj.statusCode() == 200) {
					System.out.println("Description: Success");
      
              if (response.get("account") != null) {      
              if (response.get("account.resourceId") != null) {  
                MatcherAssert.assertThat(response.get("account.resourceId"), instanceOf(String.class));  
          }
      
              if (response.get("account.iban") != null) {  
                MatcherAssert.assertThat(response.get("account.iban"), instanceOf(String.class));  
          }
      
              if (response.get("account.bic") != null) {  
                MatcherAssert.assertThat(response.get("account.bic"), instanceOf(String.class));  
          }
      
              if (response.get("account.pan") != null) {  
                MatcherAssert.assertThat(response.get("account.pan"), instanceOf(String.class));  
          }
      
              if (response.get("account.bban") != null) {  
                MatcherAssert.assertThat(response.get("account.bban"), instanceOf(String.class));  
          }
      
              if (response.get("account.currency") != null) {  
                MatcherAssert.assertThat(response.get("account.currency"), instanceOf(String.class));  
          }
      
              if (response.get("account.accountType") != null) {  
                MatcherAssert.assertThat(response.get("account.accountType"), instanceOf(String.class));  
          }
      
              if (response.get("account.cashAccountType") != null) {  
                MatcherAssert.assertThat(response.get("account.cashAccountType"), instanceOf(String.class));  
          }
      
              if (response.get("account.name") != null) {  
                MatcherAssert.assertThat(response.get("account.name"), instanceOf(String.class));  
          }
      
              if (response.get("account.balances") != null) {        
                  for (int i = 0; i < response.getList("account.balances").size(); i++) {      
              if (response.get("account.balances["+ i +"].balanceType") != null) {  
                MatcherAssert.assertThat(response.get("account.balances["+ i +"].balanceType"), instanceOf(String.class));  
          }
      
              if (response.get("account.balances["+ i +"].lastChangeDateTime") != null) {  
                MatcherAssert.assertThat(response.get("account.balances["+ i +"].lastChangeDateTime"), instanceOf(String.class));  
          }
      
              if (response.get("account.balances["+ i +"].referenceDate") != null) {  
                MatcherAssert.assertThat(response.get("account.balances["+ i +"].referenceDate"), instanceOf(String.class));  
          }
      
              if (response.get("account.balances["+ i +"].balanceAmount") != null) {      
              if (response.get("account.balances["+ i +"].balanceAmount.currency") != null) {  
                MatcherAssert.assertThat(response.get("account.balances["+ i +"].balanceAmount.currency"), instanceOf(String.class));  
          }
      
              if (response.get("account.balances["+ i +"].balanceAmount.amount") != null) {  
                MatcherAssert.assertThat(response.get("account.balances["+ i +"].balanceAmount.amount"), instanceOf(Integer.class));  
          }
  
          }
        
                    }    
                MatcherAssert.assertThat(response.getList("account.balances"), instanceOf(List.class));
  
          }
      
              if (response.get("account._links") != null) {      
              if (response.get("account._links.href") != null) {  
                MatcherAssert.assertThat(response.get("account._links.href"), instanceOf(String.class));  
          }
  
          }
  
          }
				}
  
            }  
    }
}
