// ********RoostGPT********
/*
Test generated by RoostGPT for test rbi-swagger using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated for /v1/accounts_get for http method type GET in rest-assured framework

RoostTestHash=5144dc9ece


*/

// ********RoostGPT********

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project pom-manipulation-annotation: No tests were executed!  (Set -DfailIfNoTests=false to ignore this error.) -> [Help 1]
[ERROR]
